name: "Home Automation Diagnostics MCP"
slug: "ha_diag_mcp"
description: "MCP server providing Home Assistant diagnostics tools over Streamable HTTP"
version: "0.1.16"
startup: application
boot: auto
init: false

arch:
  - amd64
  - aarch64

homeassistant_api: true
hassio_api: true
hassio_role: default

map:
  - addon_config:rw

options:
  log_level: info
  allow_origin: "*"
schema:
  log_level: list(trace|debug|info|warn|error)
  allow_origin: str

ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Home Automation Diagnostics MCP"

host_network: false

image: "chrischiaro/ha-diag-mcp-addon-{arch}"